import { IResponse } from './../../model/IResponse';
/**
 * Team Investment Tool
 * Team Investment Tool
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from '@angular/core';
import { HttpClient, HttpEvent, HttpHeaders, HttpResponse, HttpParams } from '@angular/common/http';

import { BASE_PATH }  from '../variables';
import { Configuration } from '../configuration';
import { Observable } from 'rxjs';

import { IEmployee } from '../../model/IEmployee';
import { LocalService } from '../cookie/local.service';
import { CustomHttpUrlEncodingCodec } from '../encoder';
import { Cookie } from 'src/app/enumeration/cookie.enum';


@Injectable()
export class LoginService {

    protected basePath = 'https://clerkvest.com/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, private local: LocalService, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Generate Api Key from Login Token
     * Returns a Api Key
     * @param token Login Token
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getApiKey(token: string, observe?: 'body', reportProgress?: boolean): Observable<IResponse>;
    public getApiKey(token: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<IResponse>>;
    public getApiKey(token: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<IResponse>>;
    public getApiKey(token: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (token === null || token === undefined) {
            throw new Error('Required parameter token was null or undefined when calling getApiKey.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<IEmployee>(`${this.basePath}/token/${encodeURIComponent(String(token))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

        /**
     * invite
     * 
     * @param mail mail
     * @param accountNonExpired 
     * @param accountNonLocked 
     * @param authorities0Authority 
     * @param companyId 
     * @param credentialsNonExpired 
     * @param employeeId 
     * @param enabled 
     * @param password 
     * @param token 
     * @param username 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public invite(mail: string, accountNonExpired?: boolean, accountNonLocked?: boolean, authorities0Authority?: string, companyId?: number, credentialsNonExpired?: boolean, employeeId?: number, enabled?: boolean, password?: string, token?: string, username?: string, observe?: 'body', reportProgress?: boolean): Observable<String>;
    public invite(mail: string, accountNonExpired?: boolean, accountNonLocked?: boolean, authorities0Authority?: string, companyId?: number, credentialsNonExpired?: boolean, employeeId?: number, enabled?: boolean, password?: string, token?: string, username?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<String>>;
    public invite(mail: string, accountNonExpired?: boolean, accountNonLocked?: boolean, authorities0Authority?: string, companyId?: number, credentialsNonExpired?: boolean, employeeId?: number, enabled?: boolean, password?: string, token?: string, username?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<String>>;
    public invite(mail: string, accountNonExpired?: boolean, accountNonLocked?: boolean, authorities0Authority?: string, companyId?: number, credentialsNonExpired?: boolean, employeeId?: number, enabled?: boolean, password?: string, token?: string, username?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (mail === null || mail === undefined) {
            throw new Error('Required parameter mail was null or undefined when calling inviteUsingPOST.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (accountNonExpired !== undefined && accountNonExpired !== null) {
            queryParameters = queryParameters.set('accountNonExpired', <any>accountNonExpired);
        }
        if (accountNonLocked !== undefined && accountNonLocked !== null) {
            queryParameters = queryParameters.set('accountNonLocked', <any>accountNonLocked);
        }
        if (authorities0Authority !== undefined && authorities0Authority !== null) {
            queryParameters = queryParameters.set('authorities[0].authority', <any>authorities0Authority);
        }
        if (companyId !== undefined && companyId !== null) {
            queryParameters = queryParameters.set('companyId', <any>companyId);
        }
        if (credentialsNonExpired !== undefined && credentialsNonExpired !== null) {
            queryParameters = queryParameters.set('credentialsNonExpired', <any>credentialsNonExpired);
        }
        if (employeeId !== undefined && employeeId !== null) {
            queryParameters = queryParameters.set('employeeId', <any>employeeId);
        }
        if (enabled !== undefined && enabled !== null) {
            queryParameters = queryParameters.set('enabled', <any>enabled);
        }
        if (password !== undefined && password !== null) {
            queryParameters = queryParameters.set('password', <any>password);
        }
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('token', <any>token);
        }
        if (username !== undefined && username !== null) {
            queryParameters = queryParameters.set('username', <any>username);
        }
        if (mail !== undefined && mail !== null) {
            queryParameters = queryParameters.set('mail', <any>mail);
        }

        let headers = this.defaultHeaders;

        // authentication (APIKeyHeader) required
        headers = headers.set('Authorization', 'Bearer '  + this.local.get(Cookie.TOKEN));

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<String>(`${this.basePath}/invite`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }
}
