/**
 * Team Investment Tool
 * Team Investment Tool
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
export interface ICompany {
    id?: number;
    name?: string;
    domain?: string;
    image?: string;
    payAmount?: number;
    payInterval?: number;
    inviteOnly?: boolean;
}
