/**
 * Team Investment Tool
 * Team Investment Tool
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {ICompany} from './ICompany';


export interface IEmployee {
    employee_id?: number;
    company?: ICompany;
    email?: string;
    balance?: number;
    token?: string;
    firstname?: string;
    lastname?: string;
    nickname?: string;
    is_admin?: boolean;
}
