/**
 * Team Investment Tool
 * Team Investment Tool
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@example.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {IEmployee} from './IEmployee';


export interface IProject {
    project_id?: number;
    employee_id?: IEmployee;
    link?: string;
    title?: string;
    description?: string;
    goal?: number;
    invested_in?: number;
    reached?: boolean;
    image?: string;
    created_at?: Date;
    funded_at?: Date;
}
